### ISSUE TITLE
New In Theaters Alternates

### ISSUE THREAD

**Issue by jewbmx** [I-A-C/script.module.exodusredux#8]
Decided to dip back into this because i dont like the other ones that me and doko found anymore.

Test them with your version commented out before removing what ya already got incase you dont like em ;)  (short url isnt the same one i was tossin around before now.)

`# New style and personally think its the best choice. hands down
        self.theaters_link = 'https://www.imdb.com/showtimes/location?ref_=inth_ov_sh_sm'
        # Old one renamed and altered to to updated codes, havent seen any issues yet.
        self.theatersOld_link = 'http://www.imdb.com/search/title?title_type=feature&num_votes=1000,&countries=us&languages=en&release_date=date[90],date[0]&sort=release_date,desc&count=40&start=1'`

**Comment by I-A-C** [comment]
This works good for me.  Since I live in a big city with lots of theaters, this returns a well populated list of "In Theaters" movies.  Right now I'm getting 81 movie listings.  However, I have quite a few small cinema type of theaters that show older movies.  So I have a bunch of older movies like Pulp Fiction and Big Lebowski showing up that can easily be pruned.  Adding `&release_date=date[90],date[0`] prunes the list to about 40 movies.

On the downside however, if I lived in Anchorage, Alaska  this list would only pull 13 movies.

**Comment by jewbmx** [comment]
I decided to add both links to my addon to counter any issues. the socond one can be altered with a ton of options if ya check out the advanced search on their site.

Also should mention that i didnt make this post for a real issue lol, since this has become the new hotspot for exo/cov forkers i just thought id share another fix people might be interested in lol
